### ISSUE TITLE
change repo name

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Peworld-Web#1]
please change repo name from Peworld-FE to peworld-web

**Comment by suprayogo** [comment]
![a](https://github.com/suprayogo/Peworld-Web/assets/126061696/dbc275dd-1cc8-455e-8e0f-4e125c24e08d)

I've fixed it

**Comment by kubil-ismail** [comment]
done
<img width="1680" alt="Screenshot 2023-08-10 at 00 53 28" src="https://github.com/suprayogo/Peworld-Web/assets/49361887/f4ec079c-f87b-4966-bccb-6e979c7d601a">
