### ISSUE TITLE
Fix navbar distance content

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Peworld-Web#2]
Please fix navbar content aligment navigation don't to far with left content
![Screenshot 2023-08-07 151458](https://github.com/suprayogo/Peworld-FE/assets/49361887/36a8ba82-eddb-4f12-b2be-66b24aadc02e)

**Comment by suprayogo** [comment]
![a](https://github.com/suprayogo/Peworld-FE/assets/126061696/95435adb-cc87-421d-afe0-593c1dfe43cb)

I've fixed

**Comment by kubil-ismail** [comment]
Done
terlalu lama untuk menunggu berhasil register
<img width="1680" alt="Screenshot 2023-08-10 at 00 59 57" src="https://github.com/suprayogo/Peworld-Web/assets/49361887/9f8211fc-f884-41ba-8306-a6360869ad25">
