### ISSUE TITLE
Cannot update profile photo

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Peworld-Web#3]
Check  upload photo profile features

**Comment by suprayogo** [comment]
![a](https://github.com/suprayogo/Peworld-FE/assets/126061696/4b43f19d-8eea-48fc-9346-65b71b8db934)

I've fixed it

**Comment by kubil-ismail** [comment]
update photo successfuly
<img width="1680" alt="Screenshot 2023-08-10 at 01 02 18" src="https://github.com/suprayogo/Peworld-Web/assets/49361887/64589dea-f1ef-4a04-a3df-877fdb770c4d">
