### ISSUE TITLE
Fix aligment input date in job experience

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Peworld-Web#4]
![Screenshot (131)](https://github.com/suprayogo/Peworld-FE/assets/49361887/a47e81d9-2e5f-444a-91e9-394e6f1cc7e6)

**Comment by suprayogo** [comment]
![a](https://github.com/suprayogo/Peworld-FE/assets/126061696/173cdbfc-a28b-48b7-b468-7742f603b029)


I've fixed

**Comment by kubil-ismail** [comment]
Done
<img width="1680" alt="Screenshot 2023-08-10 at 01 04 18" src="https://github.com/suprayogo/Peworld-Web/assets/49361887/30245933-857c-4c47-ba3e-aefddec4982a">
