### ISSUE TITLE
After edit profile got this error

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Peworld-Web#5]
Please check if i have edit my profile i got this error
![Screenshot (133)](https://github.com/suprayogo/Peworld-FE/assets/49361887/7817c09e-4f7e-4486-b367-916d6917ae65)
![Screenshot (132)](https://github.com/suprayogo/Peworld-FE/assets/49361887/7763ca81-235b-4293-b955-83da0bf81dbb)

**Comment by suprayogo** [comment]
![a](https://github.com/suprayogo/Peworld-FE/assets/126061696/75e6dea8-4028-4565-bfd4-db27e103f6a2)


I have fixed it to display an error message

**Comment by kubil-ismail** [comment]
done
<img width="1680" alt="Screenshot 2023-08-10 at 01 07 26" src="https://github.com/suprayogo/Peworld-Web/assets/49361887/7a9c0d67-b3eb-45fb-a8c4-0ace60efc553">
